### ISSUE TITLE
@font-face alters relative URLs

### ISSUE THREAD

**Issue by stevenvachon** [SLaks/Styliner#26]
Before:
```css
@font-face {
  font-family: name;
  src: url("../font.woff2") format("woff2"), url("../font.woff") format("woff");
}
```
After:
```css
@font-face {
  font-family: name;
  src: url("../font.woff2") format("woff2"), url("font.woff") format("woff");
}
```

Notice that the `../` on the second `url()` gets removed.
