### ISSUE TITLE
unmatched pseudo-class :focus-visible

### ISSUE THREAD

**Issue by RaschidJFR** [SLaks/Styliner#32]
When trying to process a .css file that contains pseudo-element `:focus-visible`, the "unmatched pseudo-class" error is thrown.

```css
:focus-visible {
  outline: 0 !important; }
```

Using version: styliner@1.0.4
